migrate(
  (app) => {
    const todos = new Collection({
      name: 'app_todo_todos',
      type: 'base',
      system: false,
      listRule: '',
      viewRule: '',
      createRule: '',
      updateRule: '',
      deleteRule: '',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text_id_todos',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          hidden: false,
          id: 'text_title_todo',
          max: 0,
          min: 1,
          name: 'title',
          presentable: true,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'text_status_tod',
          max: 64,
          min: 0,
          name: 'status',
          presentable: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'editor_notes_to',
          maxSize: 0,
          name: 'notes',
          presentable: false,
          required: false,
          system: false,
          type: 'editor',
        },
        {
          hidden: false,
          id: 'autodate_created',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: true,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate_updated',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: true,
          type: 'autodate',
        },
      ],
      indexes: [],
    });

    const events = new Collection({
      name: 'app_todo_events',
      type: 'base',
      system: false,
      listRule: '',
      viewRule: '',
      createRule: '',
      updateRule: '',
      deleteRule: '',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text_id_events',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          hidden: false,
          id: 'text_type_event',
          max: 128,
          min: 1,
          name: 'type',
          presentable: true,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'text_policy_evt',
          max: 64,
          min: 0,
          name: 'policy',
          presentable: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'text_summary_ev',
          max: 0,
          min: 0,
          name: 'summary',
          presentable: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'json_payload_ev',
          maxSize: 0,
          name: 'payload',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'autodate_created_',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: true,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate_updated_',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: true,
          type: 'autodate',
        },
      ],
      indexes: [],
    });

    app.save(todos);
    return app.save(events);
  },
  (app) => {
    const todos = app.findCollectionByNameOrId('app_todo_todos');
    const events = app.findCollectionByNameOrId('app_todo_events');
    app.delete(todos);
    return app.delete(events);
  }
);
